#!/bin/sh
CORE=$1
PREFIX="/home/${USER}/wine/altium/current"
DXPPATH="C:\Program Files\Altium\AD17"
DXPEXEC="DXP.EXE"

if [[ -z $CORE ]]; then
	CORE=0x08
fi

env WINEDEBUG=-all WINEARCH=win32 WINEPREFIX="$PREFIX" wine start /d "$DXPPATH" "$DXPEXEC"
